// adminId is injected at runtime by the seed runner
const getDocuments = (adminId) => [
  {
    title: 'Introduction to Computer Science – Syllabus',
    category: 'Syllabus',
    description: 'Complete syllabus for the Introduction to Computer Science course covering data structures, algorithms, and programming fundamentals.',
    fileName: 'cs101-syllabus.pdf',
    fileUrl: '/uploads/cs101-syllabus.pdf',
    fileSize: 512000,
    mimeType: 'application/pdf',
    visibleToAll: true,
    requireSignature: false,
    uploadedBy: adminId,
  },
  {
    title: 'Advanced Calculus Lecture Notes – Unit 1',
    category: 'Course Material',
    description: 'Detailed lecture notes for Unit 1 of Advanced Calculus including limits, continuity, and differentiation.',
    fileName: 'calculus-unit1-notes.pdf',
    fileUrl: '/uploads/calculus-unit1-notes.pdf',
    fileSize: 1048576,
    mimeType: 'application/pdf',
    visibleToAll: true,
    requireSignature: false,
    uploadedBy: adminId,
  },
  {
    title: 'Scholarship Application Guidelines – 2024',
    category: 'Circular',
    description: 'Official circular outlining eligibility criteria, deadlines, and required documents for all scholarship programs.',
    fileName: 'scholarship-guidelines-2024.pdf',
    fileUrl: '/uploads/scholarship-guidelines-2024.pdf',
    fileSize: 256000,
    mimeType: 'application/pdf',
    visibleToAll: true,
    requireSignature: true,
    uploadedBy: adminId,
  },
  {
    title: 'End Semester Exam Time Table – Nov 2024',
    category: 'Exam Schedule',
    description: 'Official end-semester examination schedule for all departments, November 2024.',
    fileName: 'exam-timetable-nov2024.pdf',
    fileUrl: '/uploads/exam-timetable-nov2024.pdf',
    fileSize: 180000,
    mimeType: 'application/pdf',
    visibleToAll: true,
    requireSignature: false,
    uploadedBy: adminId,
  },
  {
    title: 'Research Publication – AI in Education',
    category: 'Research Paper',
    description: 'Faculty research paper on the impact of AI-powered tools in higher education.',
    fileName: 'ai-education-research.pdf',
    fileUrl: '/uploads/ai-education-research.pdf',
    fileSize: 2097152,
    mimeType: 'application/pdf',
    visibleToAll: false,
    requireSignature: false,
    uploadedBy: adminId,
  },
];

module.exports = getDocuments;
