// studentMap: { name -> userId }  adminId injected at runtime
const getQueries = (studentMap, adminId) => [
  {
    student: studentMap['Alice Johnson'],
    studentName: 'Alice Johnson',
    registerNumber: 'REG-2023-001',
    subject: 'Semester Registration Portal Issue',
    message: "Issue with the online semester registration portal. It won't let me select elective courses. I've tried three browsers and the problem persists. Kindly look into this urgently.",
    status: 'Pending',
    adminReply: '',
    resolvedBy: null,
    resolvedAt: null,
    createdAt: new Date('2023-10-24'),
  },
  {
    student: studentMap['Mark Smith'],
    studentName: 'Mark Smith',
    registerNumber: 'REG-2023-042',
    subject: 'Official Transcript Request',
    message: 'Requesting an official transcript copy for an internship application deadline next Friday. I need it stamped and signed by the registrar.',
    status: 'Resolved',
    adminReply: 'Your transcript has been processed and sent to your registered email. Please collect the physical copy from the office.',
    resolvedBy: adminId,
    resolvedAt: new Date('2023-10-23T15:30:00'),
    createdAt: new Date('2023-10-23'),
  },
  {
    student: studentMap['Elena Rodriguez'],
    studentName: 'Elena Rodriguez',
    registerNumber: 'REG-2023-115',
    subject: 'Library Access Card Deactivated',
    message: 'My library access card seems to be deactivated since this morning. Can you please check and reactivate it? I have an assignment due tomorrow.',
    status: 'Pending',
    adminReply: '',
    resolvedBy: null,
    resolvedAt: null,
    createdAt: new Date('2023-10-22'),
  },
  {
    student: studentMap['David Chen'],
    studentName: 'David Chen',
    registerNumber: 'REG-2023-088',
    subject: 'Campus Dining Feedback',
    message: 'Feedback on campus dining: The variety of vegetarian options in Hall B has improved significantly. Thank you for addressing previous feedback. Keep it up!',
    status: 'Resolved',
    adminReply: 'Thank you for your positive feedback! We have shared it with the dining committee.',
    resolvedBy: adminId,
    resolvedAt: new Date('2023-10-21T10:00:00'),
    createdAt: new Date('2023-10-21'),
  },
  {
    student: studentMap['Linda White'],
    studentName: 'Linda White',
    registerNumber: 'REG-2023-156',
    subject: 'Urgent: Scholarship Deadline & Missing Documents',
    message: 'Urgent query regarding the upcoming scholarship deadline and missing documents in my file. The portal shows my income certificate is missing but I submitted it last week. Please resolve ASAP.',
    status: 'Urgent',
    adminReply: '',
    resolvedBy: null,
    resolvedAt: null,
    createdAt: new Date('2023-10-21'),
  },
];

module.exports = getQueries;
